services:
  - type: web
    name: portfolio-web
    env: python
    buildCommand: "cd ../client && npm install && npm run build"
    startCommand: "gunicorn app:app"
    workingDir: server  # ✅ Tell Render to run from the server folder
    buildFilter:
      paths:
        - client/**
        - server/**
        - render.yaml
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
