services:
  - type: web
    name: portfolio-web
    env: python
    workingDir: server

    buildCommand: |
      echo "🔧 Building client app..."
      cd ../client
      npm install
      npm run build

    startCommand: |
      echo "🚀 Starting Flask app..."
      gunicorn app:app

    buildFilter:
      paths:
        - client/**
        - server/**
        - render.yaml

    envVars:
      - key: PYTHON_VERSION
        value: 3.10
