services:
  - type: web
    name: portfolio-web
    env: python
    buildCommand: |
      cd client
      npm install
      npm run build
    startCommand: gunicorn server.app:app
    buildFilter:
      paths:
        - client/**
        - server/**
        - render.yaml
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    staticPublishPath: client/dist
