services:
  - type: web
    name: portfolio-web
    env: python
    buildCommand: "cd client && npm install && npm run build"
    startCommand: "gunicorn --access-logfile - --error-logfile - app:app"
    workingDir: server
    buildFilter:
      paths:
        - client/**
        - server/**
        - render.yaml
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
