services:
  - type: web
    name: KIRTANSHAH-WEBDEV
    env: python
    buildCommand: |
      cd client
      npm install
      npm run build
      cd ..
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: server